grafana:
  adminPassword: password

nodeExporter:
  enabled: false

prometheus:
  prometheusSpec:
    containers:
    # fix for jaeger injection bug: https://github.com/helm/charts/issues/22769
    - name: prometheus
      env:
      - name: JAEGER_AGENT_PORT
        value: "5755"  
    additionalScrapeConfigs:
    - job_name: 'app-metrics'
      scrape_interval: 5s
      metrics_path: /metrics
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - apps